name: Coverage

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request_target:
    branches:
      - develop
      - main
jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
