name: Coverage

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    type: [opened, reopened, synchronized]
jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
      - run: npm install
      -
