name: Coverage

on:
  push:
    branches:
      - 'main'
      - 'develop'
    pull_request_target:
      - 'main'
      - 'develop'
jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
