name: Coverage

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request_target:
    branches:
      - main
      - develop
jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
    steps:
      - uses: actions/checkout@v3
      # - run: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
